version: '3.9'

services:
  django:
    container_name: todoapp
    build: todolist_project
    ports: 
      - 8000:8000
    command: python manage.py runserver 0.0.0.0:8000

volumes:
  elasticsearch-data:
    driver: local