# Generated by Django 4.0.4 on 2022-04-17 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FutureTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('future_task_title', models.CharField(max_length=200)),
                ('slug_field', models.SlugField(blank=True, default='')),
            ],
        ),
    ]
