# Generated by Django 4.0.4 on 2022-04-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_delete_futuretask_rename_compeleted_task_completed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='completed',
            new_name='complete',
        ),
    ]
